workspace:
  base: /checkup

kind: pipeline
name: checkup

steps:
- name: test-postgres
  image: golang:1.14
  pull: always
  commands:
    - make test-postgres
    - make build-postgres

- name: test-sqlite
  image: golang:1.14
  pull: always
  commands:
    - make test-sqlite
    - make build-sqlite

services:
- name: postgres-test-db
  image: postgres:12-alpine
  environment:
    POSTGRES_PASSWORD: test
    POSTGRES_USER: test
    POSTGRES_DB: test